/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_rony;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class bangunruang extends javax.swing.JFrame {
double alasempat,jbola,jjbola,rrttabung,tempat,operasi,operasikerucut,tkerucut,rkerucut,tttabung,rrtabung,operasitabung,rrbola,operasibola,lalastiga,ttinggitiga,operasitiga;

    /**
     * Creates new form bangunruang
     */
    public bangunruang() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        tombolbalok = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tombolempat = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tomboltabung = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tombolkerucut = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tombolprisma = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tombolbola = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tomboltiga = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tombolkubus = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        panjangbalok = new javax.swing.JTextField();
        lebarbalok = new javax.swing.JTextField();
        hitungbalok = new javax.swing.JButton();
        tinggibalok = new javax.swing.JTextField();
        hasilbalok = new javax.swing.JTextField();
        risetbalok = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        luasalasempat = new javax.swing.JTextField();
        tinggiempat = new javax.swing.JTextField();
        hasilempat = new javax.swing.JTextField();
        hitungempat = new javax.swing.JButton();
        daleteempat = new javax.swing.JButton();
        backempat = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        tinggikerucut = new javax.swing.JTextField();
        jarikerucut = new javax.swing.JTextField();
        hasilkeruct = new javax.swing.JTextField();
        hitungkerucut = new javax.swing.JButton();
        hapuskerucut = new javax.swing.JButton();
        backkerucut = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        luasalasprisma = new javax.swing.JTextField();
        tinggiprisma = new javax.swing.JTextField();
        hasilprisma = new javax.swing.JTextField();
        hitungprisma = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        rtabung = new javax.swing.JTextField();
        ttabung = new javax.swing.JTextField();
        hasiltabung = new javax.swing.JTextField();
        hitungtabung = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        rrrtabung = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        alastiga = new javax.swing.JTextField();
        tinggitiga = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        hasiltiga = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        hasilkubus = new javax.swing.JTextField();
        sisi1 = new javax.swing.JTextField();
        sisi2 = new javax.swing.JTextField();
        sisi3 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        rbola = new javax.swing.JTextField();
        hasilbola = new javax.swing.JTextField();
        hitungbola = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        rrrbola = new javax.swing.JTextField();
        rrrrbola = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 57)); // NOI18N
        jLabel4.setText("Perhitungan Operasi  Bangun Ruang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 1150, -1));

        jLabel21.setFont(new java.awt.Font("ParkAvenue BT", 1, 50)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/is.PNG"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/isss.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 90, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/Picture1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 170, 1100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/Picture2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -30, 1290, 160));

        jPanel10.setBackground(new java.awt.Color(163, 173, 162));
        jPanel10.setPreferredSize(new java.awt.Dimension(2000, 1620));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolbalok.setBackground(new java.awt.Color(251, 247, 251));
        tombolbalok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolbalokMousePressed(evt);
            }
        });
        tombolbalok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/balok newww.PNG"))); // NOI18N
        tombolbalok.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 182, 178));

        jPanel10.add(tombolbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, 230));

        jLabel7.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel7.setText("LIMAS SEGI EMPAT");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        tombolempat.setBackground(new java.awt.Color(255, 255, 255));
        tombolempat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolempatMousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/limas segi empat new.jpg"))); // NOI18N

        javax.swing.GroupLayout tombolempatLayout = new javax.swing.GroupLayout(tombolempat);
        tombolempat.setLayout(tombolempatLayout);
        tombolempatLayout.setHorizontalGroup(
            tombolempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolempatLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(51, 51, 51))
        );
        tombolempatLayout.setVerticalGroup(
            tombolempatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolempatLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel10.add(tombolempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 260, 230));

        tomboltabung.setBackground(new java.awt.Color(255, 255, 255));
        tomboltabung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tomboltabungMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/tabung new.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout tomboltabungLayout = new javax.swing.GroupLayout(tomboltabung);
        tomboltabung.setLayout(tomboltabungLayout);
        tomboltabungLayout.setHorizontalGroup(
            tomboltabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tomboltabungLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        tomboltabungLayout.setVerticalGroup(
            tomboltabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tomboltabungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(tomboltabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 270, 220));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 276, -1, -1));

        tombolkerucut.setBackground(new java.awt.Color(255, 255, 255));
        tombolkerucut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolkerucutMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/kucut.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout tombolkerucutLayout = new javax.swing.GroupLayout(tombolkerucut);
        tombolkerucut.setLayout(tombolkerucutLayout);
        tombolkerucutLayout.setHorizontalGroup(
            tombolkerucutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolkerucutLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        tombolkerucutLayout.setVerticalGroup(
            tombolkerucutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolkerucutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(tombolkerucut, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 270, 230));

        tombolprisma.setBackground(new java.awt.Color(255, 255, 255));
        tombolprisma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolprismaMousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/prisma new.PNG"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout tombolprismaLayout = new javax.swing.GroupLayout(tombolprisma);
        tombolprisma.setLayout(tombolprismaLayout);
        tombolprismaLayout.setHorizontalGroup(
            tombolprismaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tombolprismaLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        tombolprismaLayout.setVerticalGroup(
            tombolprismaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolprismaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(tombolprisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 290, 230));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 276, -1, -1));

        jLabel12.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel12.setText("PRISMA");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 158, -1));

        jLabel20.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel20.setText("BALOK");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        jLabel23.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel23.setText("KERUCUT");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 158, -1));

        jLabel22.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel22.setText("TABUNG");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        tombolbola.setBackground(new java.awt.Color(255, 255, 255));
        tombolbola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolbolaMousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/bola new.PNG"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout tombolbolaLayout = new javax.swing.GroupLayout(tombolbola);
        tombolbola.setLayout(tombolbolaLayout);
        tombolbolaLayout.setHorizontalGroup(
            tombolbolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolbolaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        tombolbolaLayout.setVerticalGroup(
            tombolbolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolbolaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(177, 177, 177))
        );

        jPanel10.add(tombolbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 260, 220));

        jLabel24.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel24.setText("BOLA");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 112, -1));

        tomboltiga.setBackground(new java.awt.Color(255, 255, 255));
        tomboltiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tomboltigaMousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/limas segi tiga new.PNG"))); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout tomboltigaLayout = new javax.swing.GroupLayout(tomboltiga);
        tomboltiga.setLayout(tomboltigaLayout);
        tomboltigaLayout.setHorizontalGroup(
            tomboltigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tomboltigaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        tomboltigaLayout.setVerticalGroup(
            tomboltigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tomboltigaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(tomboltiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 270, 220));

        jLabel25.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel25.setText("LIMAS SEGI TIGA");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        tombolkubus.setBackground(new java.awt.Color(255, 255, 255));
        tombolkubus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolkubusMousePressed(evt);
            }
        });
        tombolkubus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/kubus new.PNG"))); // NOI18N
        jLabel16.setText("jLabel16");
        tombolkubus.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 163, 173));

        jPanel10.add(tombolkubus, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 470, 280, 220));

        jLabel26.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel26.setText("KUBUS");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 420, -1, -1));

        panel.addTab("tab1", jPanel10);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Lucida Calligraphy", 3, 35)); // NOI18N
        jLabel27.setText("Tinggi");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 160, -1));

        panjangbalok.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        panjangbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangbalokActionPerformed(evt);
            }
        });
        jPanel2.add(panjangbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, 40));

        lebarbalok.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        lebarbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarbalokActionPerformed(evt);
            }
        });
        jPanel2.add(lebarbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 140, 40));

        hitungbalok.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hitungbalok.setText("Count");
        hitungbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbalokActionPerformed(evt);
            }
        });
        jPanel2.add(hitungbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        tinggibalok.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        tinggibalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggibalokActionPerformed(evt);
            }
        });
        jPanel2.add(tinggibalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 140, 40));

        hasilbalok.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hasilbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilbalokActionPerformed(evt);
            }
        });
        jPanel2.add(hasilbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 140, 50));

        risetbalok.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        risetbalok.setText("Riset");
        risetbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                risetbalokActionPerformed(evt);
            }
        });
        jPanel2.add(risetbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel18.setText("Panjang");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 230, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel19.setText("Lebar");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, -1));

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, -1, -1));

        jLabel28.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel28.setText("Balok");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 260, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/wp balok p.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1270, 770));

        jLabel30.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel30.setText("Balok");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 260, -1));

        panel.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Lucida Calligraphy", 3, 53)); // NOI18N
        jLabel31.setText("LIMAS SEGI EMPAT");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 690, 130));

        jLabel32.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel32.setText("Luas Alas");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 250, 40));

        jLabel33.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel33.setText("Tinggi");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 180, -1));

        luasalasempat.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        jPanel3.add(luasalasempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 100, 40));

        tinggiempat.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        tinggiempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiempatActionPerformed(evt);
            }
        });
        jPanel3.add(tinggiempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 100, 40));

        hasilempat.setFont(new java.awt.Font("Lucida Calligraphy", 3, 33)); // NOI18N
        hasilempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilempatActionPerformed(evt);
            }
        });
        jPanel3.add(hasilempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 130, 50));

        hitungempat.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hitungempat.setText("Count");
        hitungempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungempatActionPerformed(evt);
            }
        });
        jPanel3.add(hitungempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 140, -1));

        daleteempat.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        daleteempat.setText("Dalete");
        daleteempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daleteempatActionPerformed(evt);
            }
        });
        jPanel3.add(daleteempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, -1, -1));

        backempat.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        backempat.setText("Back");
        backempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backempatActionPerformed(evt);
            }
        });
        jPanel3.add(backempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnnnn.jpg"))); // NOI18N
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 950));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnnnn.jpg"))); // NOI18N
        jLabel61.setText("jLabel61");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 110, -1));

        panel.addTab("tab3", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel35.setText("KERUCUT");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 380, -1));

        jLabel36.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel36.setText("Tinggi");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 180, -1));

        jLabel37.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel37.setText("Jari-Jari");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 240, -1));

        tinggikerucut.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        jPanel4.add(tinggikerucut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 90, 40));

        jarikerucut.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jPanel4.add(jarikerucut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 90, 40));

        hasilkeruct.setFont(new java.awt.Font("Lucida Calligraphy", 3, 33)); // NOI18N
        jPanel4.add(hasilkeruct, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 150, 50));

        hitungkerucut.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hitungkerucut.setText("Count");
        hitungkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungkerucutActionPerformed(evt);
            }
        });
        jPanel4.add(hitungkerucut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        hapuskerucut.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hapuskerucut.setText("Dalete");
        hapuskerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapuskerucutActionPerformed(evt);
            }
        });
        jPanel4.add(hapuskerucut, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        backkerucut.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        backkerucut.setText("Back");
        backkerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backkerucutActionPerformed(evt);
            }
        });
        jPanel4.add(backkerucut, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnnn.jpg"))); // NOI18N
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 1240, 960));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnn.jpg"))); // NOI18N
        jLabel62.setText("jLabel62");
        jPanel4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 210, -1));

        panel.addTab("tab4", jPanel4);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel38.setText("PRISMA");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 350, -1));

        jLabel40.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel40.setText("Luas Alas");
        jPanel7.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 250, -1));

        jLabel41.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel41.setText("Tinggi");
        jPanel7.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 200, -1));

        luasalasprisma.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jPanel7.add(luasalasprisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 90, 40));

        tinggiprisma.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        jPanel7.add(tinggiprisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 90, 40));

        hasilprisma.setFont(new java.awt.Font("Lucida Calligraphy", 3, 33)); // NOI18N
        jPanel7.add(hasilprisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 140, 50));

        hitungprisma.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hitungprisma.setText("Count");
        hitungprisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungprismaActionPerformed(evt);
            }
        });
        jPanel7.add(hitungprisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        jButton3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton3.setText("Dalete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnnn.jpg"))); // NOI18N
        jPanel7.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1200, 1210));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnnn.jpg"))); // NOI18N
        jLabel63.setText("jLabel63");
        jPanel7.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        panel.addTab("tab6", jPanel7);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel43.setText("TABUNG");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 370, -1));

        jLabel44.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel44.setText("Jari-Jari");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 220, 70));

        jLabel45.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel45.setText("Tinggi");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 200, -1));

        rtabung.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        jPanel6.add(rtabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 100, 40));

        ttabung.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        jPanel6.add(ttabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 100, 40));

        hasiltabung.setFont(new java.awt.Font("Lucida Calligraphy", 3, 35)); // NOI18N
        hasiltabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasiltabungActionPerformed(evt);
            }
        });
        jPanel6.add(hasiltabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 140, 50));

        hitungtabung.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hitungtabung.setText("Count");
        hitungtabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungtabungActionPerformed(evt);
            }
        });
        jPanel6.add(hitungtabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jButton5.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton5.setText("Dalete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jButton6.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, -1, -1));

        jLabel60.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel60.setText("Jari-Jari ");
        jPanel6.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        rrrtabung.setFont(new java.awt.Font("Lucida Calligraphy", 3, 26)); // NOI18N
        rrrtabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rrrtabungActionPerformed(evt);
            }
        });
        jPanel6.add(rrrtabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 100, 40));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnn.jpg"))); // NOI18N
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 780));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnn.jpg"))); // NOI18N
        jLabel64.setText("jLabel64");
        jPanel6.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, -1));

        panel.addTab("tab5", jPanel6);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel50.setText("LIMAS SEGI TIGA");
        jPanel11.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 610, -1));

        jLabel51.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel51.setText("Luas Alas");
        jPanel11.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 290, -1));

        jLabel52.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel52.setText("Tinggi");
        jPanel11.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 190, -1));

        alastiga.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jPanel11.add(alastiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 100, 40));

        tinggitiga.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jPanel11.add(tinggitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 100, 40));

        jButton2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton2.setText("Count");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jButton9.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton9.setText("Dalete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jButton10.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton10.setText("Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, -1, -1));

        hasiltiga.setFont(new java.awt.Font("Lucida Calligraphy", 3, 34)); // NOI18N
        jPanel11.add(hasiltiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 110, 50));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnn.jpg"))); // NOI18N
        jPanel11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1220, 750));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnn.jpg"))); // NOI18N
        jLabel67.setText("jLabel67");
        jPanel11.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, -1));

        panel.addTab("tab8", jPanel11);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel54.setText("KUBUS");
        jPanel12.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 280, -1));

        jLabel55.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel55.setText("Sisi");
        jPanel12.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 120, -1));

        jLabel56.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel56.setText("Sisi");
        jPanel12.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 110, -1));

        jLabel57.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel57.setText("Sisi");
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, -1));

        hasilkubus.setFont(new java.awt.Font("Lucida Calligraphy", 3, 35)); // NOI18N
        jPanel12.add(hasilkubus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 110, 50));

        sisi1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 25)); // NOI18N
        jPanel12.add(sisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 90, 40));

        sisi2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 25)); // NOI18N
        sisi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisi2ActionPerformed(evt);
            }
        });
        jPanel12.add(sisi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 90, 40));

        sisi3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 25)); // NOI18N
        jPanel12.add(sisi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 90, 40));

        jButton11.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton11.setText("Count");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        jButton12.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton12.setText("Dalete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        jButton13.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton13.setText("Back");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnn.jpg"))); // NOI18N
        jPanel12.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 1200));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnnnn.jpg"))); // NOI18N
        jLabel66.setText("jLabel66");
        jPanel12.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, -1, -1));

        panel.addTab("tab9", jPanel12);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Lucida Calligraphy", 3, 55)); // NOI18N
        jLabel47.setText("BOLA");
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 230, -1));

        jLabel48.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel48.setText("Jari-Jari");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 220, -1));

        rbola.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        rbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbolaActionPerformed(evt);
            }
        });
        jPanel9.add(rbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 90, 40));

        hasilbola.setFont(new java.awt.Font("Lucida Calligraphy", 3, 33)); // NOI18N
        hasilbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilbolaActionPerformed(evt);
            }
        });
        jPanel9.add(hasilbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 110, 50));

        hitungbola.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        hitungbola.setText("Count");
        hitungbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbolaActionPerformed(evt);
            }
        });
        jPanel9.add(hitungbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jButton7.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton7.setText("Dalete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        jButton8.setFont(new java.awt.Font("Lucida Calligraphy", 3, 30)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel58.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel58.setText("Jari-Jari");
        jPanel9.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 230, -1));

        jLabel59.setFont(new java.awt.Font("Lucida Calligraphy", 3, 40)); // NOI18N
        jLabel59.setText("Jari-Jari ");
        jPanel9.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        rrrbola.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jPanel9.add(rrrbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 90, 40));

        rrrrbola.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jPanel9.add(rrrrbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 90, 40));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnn.jpg"))); // NOI18N
        jPanel9.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1210, 790));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/nnnnn.jpg"))); // NOI18N
        jLabel65.setText("jLabel65");
        jPanel9.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, 800));

        panel.addTab("tab7", jPanel9);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 1360, 1020));

        jLabel9.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel9.setText("KERUCUT");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 160, -1));

        jLabel10.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel10.setText("PRISMA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 160, -1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tinggibalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggibalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggibalokActionPerformed

    private void hitungbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbalokActionPerformed
      int x = Integer.parseInt(panjangbalok.getText());
      int y = Integer.parseInt(lebarbalok.getText());
      int z = Integer.parseInt(tinggibalok.getText());
      hasilbalok.setText(String.valueOf(x*y*z));
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungbalokActionPerformed

    private void tombolbalokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolbalokMousePressed
      buatwarna(tombolbalok);
      balikinwarna(new JPanel[]{tombolempat,tombolkerucut,tombolprisma,tomboltabung,tombolbola,tomboltiga,tombolkubus});
      panel.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolbalokMousePressed

    private void tombolempatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolempatMousePressed
      buatwarna(tombolempat);
      balikinwarna(new JPanel[]{tombolbalok,tombolkerucut,tombolprisma,tomboltabung,tombolbola,tomboltiga,tombolkubus});
      panel.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolempatMousePressed

    private void tombolkerucutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkerucutMousePressed
      buatwarna(tombolkerucut);
      balikinwarna(new JPanel[]{tombolbalok,tombolempat,tombolprisma,tomboltabung,tombolbola,tomboltiga,tombolkubus});
      panel.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolkerucutMousePressed

    private void tombolprismaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolprismaMousePressed
      buatwarna(tombolprisma);
      balikinwarna(new JPanel[]{tombolbalok,tombolkerucut,tomboltabung,tombolbola,tomboltiga,tombolkubus});
      panel.setSelectedIndex(4);        // TODO add your handling code here:
    }//GEN-LAST:event_tombolprismaMousePressed

    private void tomboltabungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomboltabungMousePressed
      buatwarna(tomboltabung);
      balikinwarna(new JPanel[]{tombolbalok,tombolkerucut,tombolprisma,tombolbola,tomboltiga,tombolkubus});
      panel.setSelectedIndex(5);// TODO add your handling code here:
    }//GEN-LAST:event_tomboltabungMousePressed

    private void tombolbolaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolbolaMousePressed
      buatwarna(tombolbola);
      balikinwarna(new JPanel[]{tombolbalok,tombolkerucut,tombolprisma,tomboltabung,tomboltiga,tombolkubus});
      panel.setSelectedIndex(6);        // TODO add your handling code here:
    }//GEN-LAST:event_tombolbolaMousePressed

    private void tomboltigaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tomboltigaMousePressed
      buatwarna(tomboltiga);
      balikinwarna(new JPanel[]{tombolbalok,tombolkerucut,tombolprisma,tomboltabung,tombolbola,tombolkubus});
      panel.setSelectedIndex(7);        // TODO add your handling code here:
    }//GEN-LAST:event_tomboltigaMousePressed

    private void tombolkubusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkubusMousePressed
      buatwarna(tombolkubus);
      balikinwarna(new JPanel[]{tombolbalok,tombolkerucut,tombolprisma,tomboltabung,tombolbola,tomboltiga});
      panel.setSelectedIndex(8);        // TODO add your handling code here:
    }//GEN-LAST:event_tombolkubusMousePressed

    private void panjangbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangbalokActionPerformed

    private void hasilbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilbalokActionPerformed

    private void lebarbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarbalokActionPerformed

    private void risetbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_risetbalokActionPerformed
      panjangbalok.setText("");
      lebarbalok.setText("");
      tinggibalok.setText("");
      hasilbalok.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_risetbalokActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      panel.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tinggiempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiempatActionPerformed

    private void hasilempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilempatActionPerformed

    private void backempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backempatActionPerformed
       panel.setSelectedIndex(0); // TODO add your handling code here:
    }//GEN-LAST:event_backempatActionPerformed

    private void daleteempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daleteempatActionPerformed
        luasalasempat.setText("");
        tinggiempat.setText("");
        hasilempat.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_daleteempatActionPerformed

    private void hitungempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungempatActionPerformed
        //        int a = Integer.parseInt(luasalasempat.getText());
        //        int b = Integer.parseInt(tinggiempat.getText());
        //        hitungempat.setText(String.valueOf(1/3*a*b));
        alasempat= Double.parseDouble(luasalasempat.getText());
        tempat = Double.parseDouble(tinggiempat.getText());
        operasi = alasempat*tempat/3;
        hasilempat.setText(String.valueOf(operasi));
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungempatActionPerformed

    private void hitungkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungkerucutActionPerformed
       tkerucut = Double.parseDouble(tinggikerucut.getText());
       rkerucut = Double.parseDouble(jarikerucut.getText());
       operasikerucut = tkerucut*rkerucut*rkerucut*3.14/3;
       hasilkeruct.setText(String.valueOf(operasikerucut));
// TODO add your handling code here:
    }//GEN-LAST:event_hitungkerucutActionPerformed

    private void hapuskerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuskerucutActionPerformed
        tinggikerucut.setText("");
        jarikerucut.setText("");
        hasilkeruct.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_hapuskerucutActionPerformed

    private void backkerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backkerucutActionPerformed
        panel.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_backkerucutActionPerformed

    private void hitungprismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungprismaActionPerformed
        int a = Integer.parseInt(luasalasprisma.getText());
        int b = Integer.parseInt(tinggiprisma.getText());
        hasilprisma.setText(String.valueOf(a*b));
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungprismaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        luasalasprisma.setText("");
        tinggiprisma.setText("");
        hasilprisma.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panel.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hitungtabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungtabungActionPerformed
        tttabung = Double.parseDouble(ttabung.getText());
        rrtabung = Double.parseDouble(rtabung.getText());
        rrttabung = Double.parseDouble(rrrtabung.getText());
        operasitabung = 3.14*rrttabung*rrtabung*tttabung;
        hasiltabung.setText(String.valueOf(operasitabung));
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungtabungActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ttabung.setText("");
        rtabung.setText("");
        hasiltabung.setText("");
        rrrtabung.setText("");
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        panel.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void rbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbolaActionPerformed

    private void hitungbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbolaActionPerformed
        rrbola = Double.parseDouble(rbola.getText());
        jbola = Double.parseDouble(rrrbola.getText());
        jjbola = Double.parseDouble(rrrrbola.getText());
        operasibola = 4/3*3.14*rrbola*jbola*jjbola;
        hasilbola.setText(String.valueOf(operasibola));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungbolaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        rbola.setText("");
        rrrbola.setText("");
        rrrrbola.setText("");
        hasilbola.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        panel.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lalastiga = Double.parseDouble(alastiga.getText());
        ttinggitiga = Double.parseDouble(tinggitiga.getText());
        operasitiga = lalastiga*ttinggitiga/3;
        hasiltiga.setText(String.valueOf(operasitiga));
        // TODO add yoaur handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        alastiga.setText("");
        tinggitiga.setText("");
        hasiltiga.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        panel.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int r = Integer.parseInt(sisi1.getText());
        int t = Integer.parseInt(sisi2.getText());
        int y = Integer.parseInt(sisi3.getText());
        hasilkubus.setText(String.valueOf(r*t*y));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        sisi1.setText("");
        sisi2.setText("");
        sisi3.setText("");
        hasilkubus.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        panel.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void rrrtabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrrtabungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rrrtabungActionPerformed

    private void hasiltabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasiltabungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasiltabungActionPerformed

    private void sisi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisi2ActionPerformed

    private void hasilbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilbolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bangunruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bangunruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bangunruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bangunruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bangunruang().setVisible(true);
            }
        });
    }
private void buatwarna(JPanel pane){
    pane.setBackground(new Color(255, 0, 0));
}
private void balikinwarna(JPanel[] pane){
    for (int i=0; i<pane.length; i++){
        pane[i].setBackground(new Color(255, 255, 255));
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alastiga;
    private javax.swing.JButton backempat;
    private javax.swing.JButton backkerucut;
    private javax.swing.JButton daleteempat;
    private javax.swing.JButton hapuskerucut;
    private javax.swing.JTextField hasilbalok;
    private javax.swing.JTextField hasilbola;
    private javax.swing.JTextField hasilempat;
    private javax.swing.JTextField hasilkeruct;
    private javax.swing.JTextField hasilkubus;
    private javax.swing.JTextField hasilprisma;
    private javax.swing.JTextField hasiltabung;
    private javax.swing.JTextField hasiltiga;
    private javax.swing.JButton hitungbalok;
    private javax.swing.JButton hitungbola;
    private javax.swing.JButton hitungempat;
    private javax.swing.JButton hitungkerucut;
    private javax.swing.JButton hitungprisma;
    private javax.swing.JButton hitungtabung;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jarikerucut;
    private javax.swing.JTextField lebarbalok;
    private javax.swing.JTextField luasalasempat;
    private javax.swing.JTextField luasalasprisma;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JTextField panjangbalok;
    private javax.swing.JTextField rbola;
    private javax.swing.JButton risetbalok;
    private javax.swing.JTextField rrrbola;
    private javax.swing.JTextField rrrrbola;
    private javax.swing.JTextField rrrtabung;
    private javax.swing.JTextField rtabung;
    private javax.swing.JTextField sisi1;
    private javax.swing.JTextField sisi2;
    private javax.swing.JTextField sisi3;
    private javax.swing.JTextField tinggibalok;
    private javax.swing.JTextField tinggiempat;
    private javax.swing.JTextField tinggikerucut;
    private javax.swing.JTextField tinggiprisma;
    private javax.swing.JTextField tinggitiga;
    private javax.swing.JPanel tombolbalok;
    private javax.swing.JPanel tombolbola;
    private javax.swing.JPanel tombolempat;
    private javax.swing.JPanel tombolkerucut;
    private javax.swing.JPanel tombolkubus;
    private javax.swing.JPanel tombolprisma;
    private javax.swing.JPanel tomboltabung;
    private javax.swing.JPanel tomboltiga;
    private javax.swing.JTextField ttabung;
    // End of variables declaration//GEN-END:variables

    private JButton setText(String valueOf) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
