/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_rony;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class Perhitungan extends javax.swing.JFrame {

    /**
     * Creates new form Perhitungan
     */
    public Perhitungan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panjangbalok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tinggibalok = new javax.swing.JTextField();
        lebarbalok = new javax.swing.JTextField();
        hitungbalok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        hasilbalok = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tombolbalok = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tombolkubus = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_rony/Picture6.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1314, 190, 80, 120));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, -1, -1));

        jLabel3.setText("Perhitungan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 30));

        jLabel6.setText("tabung");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -40, 580, 90));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panjangbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangbalokActionPerformed(evt);
            }
        });
        jPanel2.add(panjangbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 11, 63, -1));

        jLabel7.setText("panjang");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 14, 55, -1));

        jLabel8.setText("Lebar");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 52, 44, -1));

        jLabel9.setText("Tingggi");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 90, -1, -1));

        tinggibalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggibalokActionPerformed(evt);
            }
        });
        jPanel2.add(tinggibalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 87, 63, -1));

        lebarbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarbalokActionPerformed(evt);
            }
        });
        jPanel2.add(lebarbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 49, 63, -1));

        hitungbalok.setText("Hitung");
        hitungbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbalokActionPerformed(evt);
            }
        });
        jPanel2.add(hitungbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 32, -1, -1));

        jButton2.setText("Riset");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));
        jPanel2.add(hasilbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));

        panel.addTab("tab1", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        panel.addTab("tab2", jPanel3);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 580, 200));

        tombolbalok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolbalokMousePressed(evt);
            }
        });

        jLabel4.setText("Balok");

        javax.swing.GroupLayout tombolbalokLayout = new javax.swing.GroupLayout(tombolbalok);
        tombolbalok.setLayout(tombolbalokLayout);
        tombolbalokLayout.setHorizontalGroup(
            tombolbalokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(tombolbalokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tombolbalokLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tombolbalokLayout.setVerticalGroup(
            tombolbalokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(tombolbalokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tombolbalokLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(tombolbalok, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        tombolkubus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombolkubusMousePressed(evt);
            }
        });

        jLabel5.setText("Kubus");

        javax.swing.GroupLayout tombolkubusLayout = new javax.swing.GroupLayout(tombolkubus);
        tombolkubus.setLayout(tombolkubusLayout);
        tombolkubusLayout.setHorizontalGroup(
            tombolkubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tombolkubusLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        tombolkubusLayout.setVerticalGroup(
            tombolkubusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(tombolkubus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panjangbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangbalokActionPerformed

    private void tinggibalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggibalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggibalokActionPerformed

    private void lebarbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarbalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarbalokActionPerformed

    private void hitungbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbalokActionPerformed
        int x = Integer.parseInt(panjangbalok.getText());
        int y = Integer.parseInt(lebarbalok.getText());
        int z = Integer.parseInt(tinggibalok.getText());
        hasilbalok.setText(String.valueOf(x*y*z));
    }//GEN-LAST:event_hitungbalokActionPerformed

    private void tombolbalokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolbalokMousePressed
       buatwarna(tombolbalok);
       balikinwarna(new JPanel[]{tombolkubus});
       panel.setSelectedIndex(0);
    }//GEN-LAST:event_tombolbalokMousePressed

    private void tombolkubusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolkubusMousePressed
       buatwarna(tombolkubus);
       balikinwarna(new JPanel[]{tombolbalok});
       panel.setSelectedIndex(1);
    }//GEN-LAST:event_tombolkubusMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perhitungan().setVisible(true);
            }
        });
    }
private void buatwarna(JPanel pane){
    pane.setBackground(new Color(255, 0, 0));
}
private void balikinwarna(JPanel[] pane){
    for (int i=0; i<pane.length; i++){
        pane[i].setBackground(new Color(255, 255, 255));
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hasilbalok;
    private javax.swing.JButton hitungbalok;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lebarbalok;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JTextField panjangbalok;
    private javax.swing.JTextField tinggibalok;
    private javax.swing.JPanel tombolbalok;
    private javax.swing.JPanel tombolkubus;
    // End of variables declaration//GEN-END:variables
}
